export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'
export const GET_CATEGORY_LIST_FAIL = 'GET_CATEGORY_LIST_FAIL'
// export const UPDATE_USER_INPUT = 'UPDATE_USER_INPUT'

